### ISSUE TITLE
merge instabot with instagramapi

### ISSUE THREAD

**Issue by mieburungdara** [LevPasha/instabot.py#107]
can someone teach me how to merge instabot with instagramapi(https://github.com/LevPasha/Instagram-API-python) to get timeline feed from user we following, so i can like my friends post that i following?

**Comment by LevPasha** [comment]
@mieburungdara maybe i merge bot and api in some future, now i have no time to do it...

**Comment by manguszta** [comment]
I'm using Instabot with InstagramAPI for a very long time to get a full list of followings (and unfollow the ones who don't follow back). Recently there's a 404 error at InstagramAPI login, but it doesn't affect anything, user list is collected successfully. However, I would like to know if I can replace instabot.py's login for InstagramAPI's login? Two logins in one bot in the same time might be suspicious to Instagram, and that's why all my accounts are getting 24-hour bans - sometimes.

Thank you, it's a nice work anyhow.

**Comment by polaroi8d** [comment]
@manguszta az instagram nagyon figyel ezekre ne hasznald oket :)))

Instagram is very strict in nowdays, you bots with gingerly :)

**Comment by dimisdas** [comment]
Locked: necrothreading

Please create a new issue and don’t bump old threads.
