### ISSUE TITLE
Running on Server

### ISSUE THREAD

**Issue by checkup45** [LevPasha/instabot.py#132]
Has anyone tried running it on a hosting platform? If so, are there any steps or minimum requirements you could share?

**Comment by inamics** [comment]
having an unlimited max_execution_time of scripts

**Comment by Shiftiing** [comment]
I want to put the script and run it on hosting platform too.
But how ?

**Comment by mkw2000** [comment]
i have it running on a cloud9 workspace

**Comment by polaroi8d** [comment]
@Shiftiing here is a good doc for it [https://docs.c9.io/docs/run-an-application](https://docs.c9.io/docs/run-an-application)

**Comment by checkup45** [comment]
What about running it on Bluehost?

**Comment by mastershaig** [comment]
What about deploying it heroku as flask app ?

**Comment by polaroi8d** [comment]
@mastershaig do you try it? :)

**Comment by mastershaig** [comment]
@polaroi8d  No, I didn't :( 

But thinking about it :) Maybe in 2 month I will share it with community. Because I don't have much time.

**Comment by polaroi8d** [comment]
@mastershaig same as here :(

**Comment by drewhga** [comment]
I have it running 24/7 on Heroku with a free dyno

**Comment by polaroi8d** [comment]
Can you tell me the heroku app link ? Easy to set up?  When you have free account in Heroku your app sometimes, go sleep or not? How much for dont do these? Thanks @drewhga

**Comment by mastershaig** [comment]
@polaroi8d  There are many services to prevent free heroku app sleep. I use [this](http://kaffeine.herokuapp.com)

**Comment by amgworkshop** [comment]
I'm running it on a 128mb NAT VPS with no problem

**Comment by drewhga** [comment]
The app link is ibot123.herokuapp.com since the app is run using a bot
process instead of a web process the above link just gives an error but it
runs fine with the console output appearing in my app logs. Yes, its fairly
easy to set up. Sleep depends on your parameters, a heroku app goes to
sleep after 30 minutes of inactivity with or without a free account. The
only disadvantage is that a free account gives you 550 hours of run time
per month but just by adding a credit card enough hours of runtime is given
you to cover the deficit

**Comment by polaroi8d** [comment]
@drewhga can you set up, in the website console log?

**Comment by drewhga** [comment]
Setup as in?

**Comment by polaroi8d** [comment]
@drewhga When you use the console, you have a log, i think about that. Its wonderfull to print in a simple website that console log. You got it?

**Comment by drewhga** [comment]
Yeah, it'd be cool but I don't think I want my console logs open for public
viewing.

**Comment by drewhga** [comment]
Should this not be closed? @polaroi8d

**Comment by polaroi8d** [comment]
Yeah, @drewhga, you answered. And i think @checkup45  is inactive.

**Comment by virginsince1997** [comment]
I KEEP GETTING FAILED BUILD WHEN TRYING TO DEPLOY A SCRIPT TO HEROKU

**Comment by polaroi8d** [comment]
@virginsince1997 Please, bro stop capslock all the time and if you need, any help, share your error, or your problem more specific, please.

**Comment by virginsince1997** [comment]
I tried installing heroku but I keep getting Build error,..

**Comment by drewhga** [comment]
Read the build log and tell me what the error code given is

**Comment by drewhga** [comment]
Which OS?. For the easier method just use the online dashboard

**Comment by wootwoot1234** [comment]
@drewhga would you mind writing up some basic instructions on how to get it running on Heroku?  I know it's a lot to ask but I'm sure there would be a lot of people that would find it useful.

**Comment by luisramirez-m** [comment]
I use https://www.pythonanywhere.com, only need upload the files, start console, and run the script. And that's it.

Sorry if it is out of topic issue.

PD. I have problems on pythonanywhere with CPU Usage on Free account with mode's 1, 2, 3 and 4. Spends very quickly what they give us for free. I use only mode 0.

**Comment by jeometry** [comment]
@luisramirez-m Thanks for the recommendation. I set up all the files and such but I am having issues connecting once I run the script. I get " Login error! Connection error!" Have you run into that error?

**Comment by luisramirez-m** [comment]
@jeometry mm you enter to instagram.com on Chrome o Firefox with your account, and say: "Yes, it's me", sometimes Instagram say "you need to verify your account with email or phone", if this happen again maybe you need to buy a proxy, because maybe the IP of pythonanywhere.com is hated for Instagram haha. I haven't problems with that.

**Comment by AdrianaVecc** [comment]
@drewhga Would you mind sharing how you set up the ProcFile to make it work? Thanks!

**Comment by jferdizzle** [comment]
Basic instructions for setting this up with Heroku, since I don't see an answer.
1. Setup instabot-py locally (follow the readme)
2. Create a Procfile with the following:
`worker: instabot-py USERNAME`
3. Push it to some Heroku app and start the worker.

Alternatively, you could run it detached on a dyno:
`heroku run:detached instabot-py USERNAME`
