### ISSUE TITLE
Stuck following 1 person?

### ISSUE THREAD

**Issue by mumzspahgetti** [LevPasha/instabot.py#190]
First off thanks a lot for sharing this, the like feature works perfectly although the bot follows 1 person and keeps on following the same person. 
Does anyone know a fix to this?
Thanks!

**Comment by mumzspahgetti** [comment]
![image](https://cloud.githubusercontent.com/assets/22212488/18542920/b22739dc-7b70-11e6-87ad-53a1eefa9518.png)

**Comment by LevPasha** [comment]
@mumzspahgetti i think you use bad #hashtag. Try something else. Bot take users for follow from hastag media.

**Comment by virginsince1997** [comment]
Please help me, I've python 3.5
On Sep 15, 2016 7:40 PM, pikuda42438@gmail.com wrote:

How can I run it in python, Do I just copy and paste it in?
On Sep 15, 2016 7:37 PM, "Pasha Lev" <notifications@github.com> wrote:

Closed #190 <https://github.com/LevPasha/instabot.py/issues/190>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LevPasha/instabot.py/issues/190#event-791146045>, or mute
the thread

**Comment by mumzspahgetti** [comment]
thanks for quick reply, but I have used lots of different hashtags and still get stuck trying to follow one person?

**Comment by ProZeeshan** [comment]
@mumzspahgetti did you fix the problem?
It same here. Whenever I increase the follow_per_day from 300 to 1000, it follows the same person. On 300 value it works fine.

**Comment by manguszta** [comment]
I noticed the same thing. It follows the first user at the same hashtag everytime. No matter how many hashtags I use. Example:
Get media id by tag: #example1
Trying to follow: 123456
Followed: 123456 #1

Get media id by tag: #example2
Trying to follow: 789123
Followed: 789123 #2

Get media id by tag: #example1
Trying to follow: 123456
Followed: 123456 #1
