### ISSUE TITLE
Follows per day = 0 doesn't work

### ISSUE THREAD

**Issue by nivong** [LevPasha/instabot.py#254]
follow_per_day=0
when selecting mode 1 it doesn't care about this setting and still follows people, unfollows and doesn't like or comment (i have let it run for around 5 min didn't do any liking apart from following)

 I just want the bot to comment and like not follow anyone. (@kemong)

**Comment by polaroi8d** [comment]
#245

**Comment by nivong** [comment]
Why would you want everything in one issue that makes no sense to me

**Comment by polaroi8d** [comment]
There is lots of same questions every week...

**Comment by nivong** [comment]
This is a bug report not a question....

**Comment by virginsince1997** [comment]
You are being rude

**Comment by nivong** [comment]
Can you elaborate your allegation?

**Comment by polaroi8d** [comment]
@nivong I think he, point to me. :sob:

**Comment by kemong** [comment]
I forgot to say that my modification is not intended to replace the original "Instabot.py" 
So, @nivong if you just want to like and comment and let the bot unfollow no one, you should use MODE 0. 
My modification disables comment features. Why? Because after a first week using original bot, my Instagram account commenting TWICE on the same photo. It becomes huge problem because that account is my client's account. His account looks spammy with that behaviour. So i make some modification, abandoning comment feature and not relying on TAG LIST to find people anymore.

**Comment by Plorenzo** [comment]
@polaroi8d @kemong I think a lot of the problems and questions that people are having are because there is no a clear explanation of the different modes and expected behaviors anywhere. Maybe I'm wrong but I think updating the Readme is a good way to solve this.

**Comment by polaroi8d** [comment]
Its ture @Plorenzo but i dont have time for it.

**Comment by nivong** [comment]
@kemong i see so basicly it's 2 bots in 1 and the settings that are editable aren't aplicable to your mod?
I get this error while using mode 1 btw:
```
Traceback (most recent call last):
stdout
20:54:27
  File &quot;runthis.py&quot;, line 68, in &lt;module&gt;
stdout
20:54:27
    feed_scanner(bot)
stdout
20:54:27
  File &quot;/usr/src/app/src/feed_scanner.py&quot;, line 29, in feed_scanner
stdout
20:54:27
    get_media_id_user_feed(self)
stdout
20:54:27
  File &quot;/usr/src/app/src/user_feed.py&quot;, line 17, in get_media_id_user_feed
stdout
20:54:28
    url = 'https://www.instagram.com/explore/tags/%s' % (random.choice(self.tag_list))
stdout
20:54:28
NameError: global name 'random' is not defined
