### ISSUE TITLE
Delay between likes

### ISSUE THREAD

**Issue by ropad** [LevPasha/instabot.py#48]
Isn't a bad thing that the bot has always the same delay between actions? I personally think that a random delay (between 3 and 15 sec) would be better delay (humans aren't so regular they [and us] are more randomized).

**Comment by nathanhope** [comment]
I have a feeling that Instagram doesn't look at iteration lengths, otherwise this wouldn't work at all. I think they  look more at overall number of likes, follows, comments, etc. within a given time period. If you think about it, it's relatively easy for any bot to randomize iterations so they probably thought it would be a waste of time to implement in their monitoring.

**Comment by ropad** [comment]
yes maybe it's so but think at that. Why when you use your smartphone you can follow as much people as you want and from a code like that that emulate user interface you can't. I think that for them is not too difficult to register user interactions delays and maybe this way is a better on.

**Comment by nathanhope** [comment]
It's possible that the AppId used in the requests from the official IG mobile app does not have the same rate restrictions that third party AppId's have (like Ink361). I could be wrong but this is how some other APIs function as well so it makes the most sense to me.

**Comment by ropad** [comment]
Yes, you're answer it's more probable.

**Comment by ropad** [comment]
>

**Comment by LevPasha** [comment]
@ropad @nathanhope 
1) I think Instagram don't analyze like delay. 
2) Bot have random delay: `like_delay` +- 10% between any like.
